# Scenario File: scenario1.toml
[scenario]
starting_day = 2
victory_condition_amount = 9
victory_condition_level = 3

# Starting conditions for crops
[crops]
carrots = 6
roses = 6
corns = 6

# Weather configuration
[weather]
RAND_SUN_MIN = 0
RAND_SUN_MAX = 5
RAND_WATER_MIN = 0
RAND_WATER_MAX = 2
MAX_WATER_CAPACITY = 10;
